###Agent config file

hostname: 'node-1'
bnInterface : 'wlan0'
ipAddress : '192.168.1.1'
bnChannel : 11
sutMac: '08:ed:b9:16:cd:8f'
controllerDL : 'tcp://192.168.1.1:8990'
controllerUL : 'tcp://192.168.1.1:8989'
