###Agent config file

hostname: 'node-3'
bnInterface : 'wlan0'
ipAddress : '192.168.1.3'
bnMask : "255.255.255.0"
bnChannel : 11
sutInterface : 'eth0'
sutMac: '08:ed:b9:16:cd:99'
controllerDL : 'tcp://192.168.1.1:8990'
controllerUL : 'tcp://192.168.1.1:8989'
