###Agent config file

hostname: 'node-3'
bnInterface : 'wlan0'
ipAddress : '192.168.1.3'
bnChannel : 11
sutMac: '08:ed:b9:16:cd:99'
controllerDL : 'tcp://192.168.1.1:8990'
controllerUL : 'tcp://192.168.1.1:8989'
