###Agent config file

hostname: 'node-1'
bnInterface : 'wlan0'
ipAddress : '192.168.1.1'
bnMask : "255.255.255.0"
bnChannel : 11
sutInterface : 'eth0'
sutMac: '08:ed:b9:16:cd:8f'
controllerDL : 'tcp://192.168.1.1:8990'
controllerUL : 'tcp://192.168.1.1:8989'
